In [1]:
import numpy as np

In [2]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [3]:
count = 0

for i in a:
    if i <0:
        count += 1
print(count)

4


In [4]:
#1
np.count_nonzero(a<0) 
    

4

In [5]:
#2
np.count_nonzero(a>=0)

8

In [7]:
#3
x = a % 2
y= x == 0 
evens = a[y]
evens

np.count_nonzero(evens >= 0)

6

In [8]:
a[x]


array([ 4,  4,  4, 10,  4, 10,  4,  4,  4,  4, 10, 10])

In [9]:
#4
add_three = a + 3

np.count_nonzero(add_three >0)

10

In [10]:
#5
square = a ** 2
square.mean()

74.0

In [11]:
square.std()

144.0243035046516

In [12]:
a.mean()

centered = a - a.mean()

centered.mean()

0.0

In [13]:
# 7 
z_score = ((a-a.mean())/(a.std()))
z_score


array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [14]:
#pt 1 exercise 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

sum_of_a = sum(a)
sum_of_a

55

In [15]:
#exercise 2
min_of_a = min(a)
min_of_a

1

In [16]:
#exercise 3
max_of_a = max(a)
max_of_a

10

In [17]:
# exercise 4 
mean_of_a = sum(a) / len(a)
mean_of_a

5.5

In [18]:
# exercise 5

product_of_a = 1
for n in a:
    product_of_a *= n
product_of_a


3628800

In [19]:
#6
squares_of_a = [number ** 2 for number in a]
squares_of_a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [20]:
# 7
odds_in_a = [odd for odd in a if odd %2]
odds_in_a

[1, 3, 5, 7, 9]

In [21]:
# 8
evens_in_a = [even for even in a if not even % 2]
evens_in_a


[2, 4, 6, 8, 10]

In [22]:
# part 2 exercises



In [38]:
#1 
b = [
    [3,4,5],
    [6,7,8]
]
b = np.array(b)

In [39]:
flattened_list = []
for numbers in b:
    for n in numbers:
        flattened_list.append(n)
flattened_list


[3, 4, 5, 6, 7, 8]

In [40]:
b.sum()

33

In [41]:
# 2 
b.min()

3

In [42]:
#3
b.max()

8

In [43]:
#4
b.mean()

5.5

In [44]:
#5
b.prod()

20160

In [45]:
#6
b**2

array([[ 9, 16, 25],
       [36, 49, 64]])

In [46]:
#7
b[b%2==1]

array([3, 5, 7])

In [47]:
#8 
b[b%2==0]

array([4, 6, 8])

In [48]:
#9
b.shape

(2, 3)

In [49]:
#10
b.T

array([[3, 6],
       [4, 7],
       [5, 8]])

In [50]:
b.reshape(1,6)

array([[3, 4, 5, 6, 7, 8]])

In [51]:
b.reshape(6,1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])